// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package tracer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tracerConnCtxT struct {
	_        structs.HostLayout
	CgroupId uint64
	StartTs  uint64
	Pid      uint32
	Comm     [16]int8
	_        [4]byte
}

type tracerConnEventT struct {
	_          structs.HostLayout
	Ts         uint64
	Pid        uint32
	Error      uint32
	Comm       [16]int8
	Family     uint16
	LocalPort  uint16
	RemotePort uint16
	Type       uint16
	LocalIp    [16]uint8
	RemoteIp   [16]uint8
	CgroupId   uint64
	ConnCount  uint64
	ConnRate   uint32
	RttAvgUs   uint32
	LifeAvgUs  uint64
	SegLen     uint32
	SndWnd     uint32
	PacketsOut uint32
	RtxRatioPm uint32
	CaState    uint8
	RtxCount   uint8
	Pad        [2]uint8
	_          [4]byte
}

type tracerStatsKeyT struct {
	_        structs.HostLayout
	CgroupId uint64
	Pid      uint32
	Family   uint16
	DstPort  uint16
	SrcIp    [16]uint8
	DstIp    [16]uint8
}

type tracerStatsT struct {
	_            structs.HostLayout
	ConnCount    uint64
	WindowStart  uint64
	ConnRate     uint32
	ConnRatePrev uint32
	RttSumUs     uint64
	RttCount     uint64
	LifeSumNs    uint64
	LifeCount    uint64
	RtxSum       uint64
	SegsSum      uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tracerMapKoEvents               = "ko_events"
	tracerMapKoSockCtx              = "ko_sock_ctx"
	tracerMapKoSockStats            = "ko_sock_stats"
	tracerProgKoDestroySock         = "ko_destroy_sock"
	tracerProgKoRecvReset           = "ko_recv_reset"
	tracerProgKoRtxSkb              = "ko_rtx_skb"
	tracerProgKoRtxSynack           = "ko_rtx_synack"
	tracerProgKoSendReset           = "ko_send_reset"
	tracerProgKoSockState           = "ko_sock_state"
	tracerVarKoFilterIgnoreLoopback = "ko_filter_ignore_loopback"
)

// loadTracer returns the embedded CollectionSpec for tracer.
func loadTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracer: %w", err)
	}

	return spec, err
}

// loadTracerObjects loads tracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tracerObjects
//	*tracerPrograms
//	*tracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTracerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerSpecs struct {
	tracerProgramSpecs
	tracerMapSpecs
	tracerVariableSpecs
}

// tracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerProgramSpecs struct {
	KoDestroySock *ebpf.ProgramSpec `ebpf:"ko_destroy_sock"`
	KoRecvReset   *ebpf.ProgramSpec `ebpf:"ko_recv_reset"`
	KoRtxSkb      *ebpf.ProgramSpec `ebpf:"ko_rtx_skb"`
	KoRtxSynack   *ebpf.ProgramSpec `ebpf:"ko_rtx_synack"`
	KoSendReset   *ebpf.ProgramSpec `ebpf:"ko_send_reset"`
	KoSockState   *ebpf.ProgramSpec `ebpf:"ko_sock_state"`
}

// tracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerMapSpecs struct {
	KoEvents    *ebpf.MapSpec `ebpf:"ko_events"`
	KoSockCtx   *ebpf.MapSpec `ebpf:"ko_sock_ctx"`
	KoSockStats *ebpf.MapSpec `ebpf:"ko_sock_stats"`
}

// tracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerVariableSpecs struct {
	KoFilterIgnoreLoopback *ebpf.VariableSpec `ebpf:"ko_filter_ignore_loopback"`
}

// tracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerObjects struct {
	tracerPrograms
	tracerMaps
	tracerVariables
}

func (o *tracerObjects) Close() error {
	return _TracerClose(
		&o.tracerPrograms,
		&o.tracerMaps,
	)
}

// tracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerMaps struct {
	KoEvents    *ebpf.Map `ebpf:"ko_events"`
	KoSockCtx   *ebpf.Map `ebpf:"ko_sock_ctx"`
	KoSockStats *ebpf.Map `ebpf:"ko_sock_stats"`
}

func (m *tracerMaps) Close() error {
	return _TracerClose(
		m.KoEvents,
		m.KoSockCtx,
		m.KoSockStats,
	)
}

// tracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerVariables struct {
	KoFilterIgnoreLoopback *ebpf.Variable `ebpf:"ko_filter_ignore_loopback"`
}

// tracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerPrograms struct {
	KoDestroySock *ebpf.Program `ebpf:"ko_destroy_sock"`
	KoRecvReset   *ebpf.Program `ebpf:"ko_recv_reset"`
	KoRtxSkb      *ebpf.Program `ebpf:"ko_rtx_skb"`
	KoRtxSynack   *ebpf.Program `ebpf:"ko_rtx_synack"`
	KoSendReset   *ebpf.Program `ebpf:"ko_send_reset"`
	KoSockState   *ebpf.Program `ebpf:"ko_sock_state"`
}

func (p *tracerPrograms) Close() error {
	return _TracerClose(
		p.KoDestroySock,
		p.KoRecvReset,
		p.KoRtxSkb,
		p.KoRtxSynack,
		p.KoSendReset,
		p.KoSockState,
	)
}

func _TracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracer_x86_bpfel.o
var _TracerBytes []byte
