// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package tracer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tracerConnCtxT struct {
	_        structs.HostLayout
	CgroupId uint64
	StartTs  uint64
	Pid      uint32
	Comm     [16]int8
	_        [4]byte
}

type tracerConnEventT struct {
	_           structs.HostLayout
	Ts          uint64
	Pid         uint32
	Error       uint32
	Comm        [16]int8
	Family      uint16
	LocalPort   uint16
	RemotePort  uint16
	Type        uint16
	LocalIp     [16]uint8
	RemoteIp    [16]uint8
	CgroupId    uint64
	LifeUs      uint64
	RttUs       uint32
	Retransmits uint32
	SegsOut     uint32
	FilterIdx   uint16
	_           [2]byte
}

type tracerKoProg struct {
	_        structs.HostLayout
	Nfilters uint32
	Npreds   uint32
	Preds    [64]struct {
		_    structs.HostLayout
		Val  uint64
		Kind uint8
		A    uint8
		B    uint8
		N    uint8
		Plen [4]uint16
		Fam  [4]uint8
		Addr [4][16]uint8
	}
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tracerMapKoCgroupVerdict = "ko_cgroup_verdict"
	tracerMapKoEvents        = "ko_events"
	tracerMapKoFilterCfg     = "ko_filter_cfg"
	tracerMapKoFilterDrops   = "ko_filter_drops"
	tracerMapKoFilterProg    = "ko_filter_prog"
	tracerMapKoRingbufDrops  = "ko_ringbuf_drops"
	tracerMapKoSockCtx       = "ko_sock_ctx"
	tracerProgKoDestroySock  = "ko_destroy_sock"
	tracerProgKoRetransmit   = "ko_retransmit"
	tracerProgKoSockState    = "ko_sock_state"
)

// loadTracer returns the embedded CollectionSpec for tracer.
func loadTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracer: %w", err)
	}

	return spec, err
}

// loadTracerObjects loads tracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tracerObjects
//	*tracerPrograms
//	*tracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTracerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerSpecs struct {
	tracerProgramSpecs
	tracerMapSpecs
	tracerVariableSpecs
}

// tracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerProgramSpecs struct {
	KoDestroySock *ebpf.ProgramSpec `ebpf:"ko_destroy_sock"`
	KoRetransmit  *ebpf.ProgramSpec `ebpf:"ko_retransmit"`
	KoSockState   *ebpf.ProgramSpec `ebpf:"ko_sock_state"`
}

// tracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerMapSpecs struct {
	KoCgroupVerdict *ebpf.MapSpec `ebpf:"ko_cgroup_verdict"`
	KoEvents        *ebpf.MapSpec `ebpf:"ko_events"`
	KoFilterCfg     *ebpf.MapSpec `ebpf:"ko_filter_cfg"`
	KoFilterDrops   *ebpf.MapSpec `ebpf:"ko_filter_drops"`
	KoFilterProg    *ebpf.MapSpec `ebpf:"ko_filter_prog"`
	KoRingbufDrops  *ebpf.MapSpec `ebpf:"ko_ringbuf_drops"`
	KoSockCtx       *ebpf.MapSpec `ebpf:"ko_sock_ctx"`
}

// tracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerVariableSpecs struct {
}

// tracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerObjects struct {
	tracerPrograms
	tracerMaps
	tracerVariables
}

func (o *tracerObjects) Close() error {
	return _TracerClose(
		&o.tracerPrograms,
		&o.tracerMaps,
	)
}

// tracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerMaps struct {
	KoCgroupVerdict *ebpf.Map `ebpf:"ko_cgroup_verdict"`
	KoEvents        *ebpf.Map `ebpf:"ko_events"`
	KoFilterCfg     *ebpf.Map `ebpf:"ko_filter_cfg"`
	KoFilterDrops   *ebpf.Map `ebpf:"ko_filter_drops"`
	KoFilterProg    *ebpf.Map `ebpf:"ko_filter_prog"`
	KoRingbufDrops  *ebpf.Map `ebpf:"ko_ringbuf_drops"`
	KoSockCtx       *ebpf.Map `ebpf:"ko_sock_ctx"`
}

func (m *tracerMaps) Close() error {
	return _TracerClose(
		m.KoCgroupVerdict,
		m.KoEvents,
		m.KoFilterCfg,
		m.KoFilterDrops,
		m.KoFilterProg,
		m.KoRingbufDrops,
		m.KoSockCtx,
	)
}

// tracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerVariables struct {
}

// tracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerPrograms struct {
	KoDestroySock *ebpf.Program `ebpf:"ko_destroy_sock"`
	KoRetransmit  *ebpf.Program `ebpf:"ko_retransmit"`
	KoSockState   *ebpf.Program `ebpf:"ko_sock_state"`
}

func (p *tracerPrograms) Close() error {
	return _TracerClose(
		p.KoDestroySock,
		p.KoRetransmit,
		p.KoSockState,
	)
}

func _TracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracer_x86_bpfel.o
var _TracerBytes []byte
