conntest:
  enabled: true

config: |
  exporters:
    - name: stdout
  tracer:
    filters:
      ignoreLoopback: false
  metrics:
    addr: ":9081"
  conntest:
    enabled: true
    listenPort: 9080
    interval: 1s
    timeout: 2s
